name: continual_learning_simulations
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - backcall=0.2.0
  - ca-certificates
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=8.0.0
  - ipykernel=6.29.4
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core
  - libcxx
  - libffi
  - libsodium
  - matplotlib-inline=0.1.7
  - ncurses
  - nest-asyncio=1.6.0
  - openssl
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.8
  - pyzmq
  - readline
  - setuptools
  - six=1.16.0
  - sqlite
  - stack_data=0.6.2
  - tk
  - tornado
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel
  - xz
  - zeromq
  - zipp=3.19.2
  - zlib
  - pip:
      - contourpy==1.1.1
      - cycler==0.12.1
      - exceptiongroup==1.2.1
      - filelock==3.15.4
      - fonttools==4.53.0
      - fsspec==2024.6.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - pathlib==1.0.1
      - pillow==10.3.0
      - pluggy==1.5.0
      - pyparsing==3.1.2
      - pytest==8.2.2
      - python-dateutil==2.9.0.post0
      - sympy==1.12.1
      - tomli==2.0.1
      - torch==2.3.1